### ISSUE TITLE
parse_numeric vs parse_number

### ISSUE THREAD

**Issue by jphalip** [swirldev/swirl_courses#329]
Recently #326 and #327 fixed an issue that was caused by the deprecation of `tidyr::extract_numeric`. The fix consisted of replacing the calls to `tidyr::extract_numeric` with `readr::parse_numeric`.

Now, the problem is that `readr::parse_numeric` itself was deprecated in `readr` v0.2.0 (https://blog.rstudio.org/2015/10/28/readr-0-2-0/) in favor of `readr::parse_number`. I'm using `readr` v1.0.0 so I'm still getting deprecation warnings.

I'm not sure how to write a proper fix that would work both for older and newer versions of `readr`.

Thank you.

EDIT: Removed some incorrect details from my original report

**Comment by seankross** [comment]
Thanks for letting me know, I'll take care of this.

**Comment by Humanavatar** [comment]
Yesterday, October 8th, I downloaded the "Getting_and_Cleaning_Data" course using install_course and got to the tidy data section today and it appears the parse_numeric vs. parse_number deprecation error is preventing my moving forward as the script "appears" to catch the deprecation message and determines there is an exception of some kind.  

In script4.R, when I use the requested "parse_numeric" function, there are three deprecation messages displayed during the validation step.  When I change the "parse_numeric" function to "parse_number", as indicated by the deprecation message, I see one deprecation message for "parse_numeric", indicating the course is executing its own version script4.R  

It appears the course using the "parse_numeric" function and the resulting deprecation warning is enough to cause the validation to fail.

At this point, I do not see how I am able to finish the Tidy Data portion of this swirl course.

**Comment by seankross** [comment]
Thanks @jphalip and @Humanavatar, this is fixed now.

**Comment by xavier-arque** [comment]
I am still having the same problem. When it comes to this point in the Tidy Data swirl course it simply can not find the function and if you try to skip it it just makes swirl to exit.

Copy from RStudio Swirl course:

 Lastly, we want the values in the class column to simply be 1, 2, ..., 5 and not
| class1, class2, ..., class5. We can use the parse_number() function from readr to
| accomplish this. To see how it works, try parse_number("class5").

> parse_number("class5")
Error: no se pudo encontrar la función (translate: can not found the function) "parse_number"
> skip()
Error in eval(expr, envir, enclos) : 
  no se pudo encontrar la función (translate: can not found the function) "parse_number"

| Leaving swirl now. Type swirl() to resume.

>

**Comment by seankross** [comment]
@xavier-arque Are you sure have the latest version of the course and the latest version of readr?

**Comment by xavier-arque** [comment]
@seankross 
Hi, You are right. I guess that my readr version is not the last one. I will try to update it. Thanks
> packageVersion("swirl")
[1] ‘2.4.2’
> packageVersion("readr")
[1] ‘0.1.1’
