### ISSUE TITLE
lesson.yaml: Invalid tag for scalar: int#base60

### ISSUE THREAD

**Issue by zoedsj** [swirldev/swirl_courses#391]
In the Getting and Cleaning Data class on lesson 'Manipulating Data with dplyr, after loading the 'dplyr' package successfullly, there was a problem as shown in the  screenshot below. i installed the course again but still couldn't deal with it. who can help me, thanks very much!
[screenshot](https://user-images.githubusercontent.com/32319802/37400884-4f57d628-27c1-11e8-864d-77966798fce9.png)

**Comment by atalv** [comment]
I also encountered the same error. Checked comments of @viking at [https://github.com/viking/r-yaml/issues/53]. Later just edited the YAML file by adding quotation marks at respective places to make it acceptable. Please unzip the attached file and replace it at:
~Documents\R\R-3.4.4\library\swirl\Courses\Getting_and_Cleaning_Data\Manipulating_Data_with_dplyr
[lesson.zip](https://github.com/swirldev/swirl_courses/files/1876089/lesson.zip)

**Comment by zoedsj** [comment]
got it !  thanks very much ^_^

**Comment by Jaebane** [comment]
Hi
I am completely new to R. Can you tell me what you mean by "adding quotation marks at respective places"? and when I downloaded "Getting and Cleaning Data" there is no folder where I can replace the file. How do I replace it?

**Comment by nitinanarwal** [comment]
Thanks @atalv . Its working now. 

@Jaebane if you are on mac. Open finder and press command+shift+g . Go to folder pop-up will open. you need to paste folder path which you can find in error message in R. For eg: 

/Library/Frameworks/R.framework/Versions/3.4/Resources/library/swirl/Courses/Getting_and_Cleaning_Data/Manipulating_Data_with_dplyr/ 

This is what i am getting . Your version maybe different so just check that path for error message. 

After you press Go button. it wil take you that directory and you will find lesson.yaml file. You just need to replace with attached file as provided by atalv.

**Comment by TonyMcode** [comment]
This worked for me on a mac:
1) download the lesson.zip from atalv
2) unzip it to see a file called lesson.yaml
3) In Finder: Go-->Go To Folder...
4) then entered the following into the "Go to the folder dialog": ~/.R/packages/swirl/Courses/Getting_and_Cleaning_Data/Manipulating_Data_with_dplyr/
5) the folder that opens has a lesson.yaml, replace it with the one from atalv

**Comment by viking** [comment]
By the way, this should be fixed in the latest version of the yaml package (2.1.19). It was released today so it may be a couple of days before mac and windows binaries are available from CRAN.

**Comment by AmaniAbbas** [comment]
@viking I still face the same problem
I have downloaded the latest yaml package , and I have tried installing the yaml lesson atalv mentioned and replaced the existing one, but yet still facing a problem downloading dplyr package in coursera lesson
this is what I see:


| Trying to install package ‘dplyr’ now...
package ‘dplyr’ successfully unpacked and MD5 sums checked

| Could not install package ‘dplyr’!
  |                                                                                          |   0%Error in seq.default(0, 1, length = nrow(e$les)) : 
  argument 'length.out' must be of length 1

| Leaving swirl now. Type swirl() to resume.

**Comment by noooo123456** [comment]
> I also encountered the same error. Checked comments of @viking at [vubiostat/r-yaml#53](https://github.com/vubiostat/r-yaml/issues/53) Later just edited the YAML file by adding quotation marks at respective places to make it acceptable. Please unzip the attached file and replace it at: ~Documents\R\R-3.4.4\library\swirl\Courses\Getting_and_Cleaning_Data\Manipulating_Data_with_dplyr [lesson.zip](https://github.com/swirldev/swirl_courses/files/1876089/lesson.zip)

I replaced it with the file from archive and it didnt help((
